---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bills-api
  namespace: egs1
spec:
  #replicas: 3
  selector:
    matchLabels:
      app: bills-api
  template:
    metadata:
      labels:
        app: bills-api
    spec:
      containers:
      - name: api
        image: registry.deti:5000/billsdivider/billsapi:20062022
        resources:
          requests:
            memory: "250Mi"
            cpu: "500m"
          limits:
            memory: "500Mi"
            cpu: "1000m"
        ports:
        - containerPort: 8000
          name: billsapi
        volumeMounts:
        - name: billsapi-secret
          mountPath: "/tmp/secrets"
          readOnly: true
      volumes:
      - name: billsapi-secret
        secret:
          secretName: billsapi-secret
---
apiVersion: v1
kind: Service
metadata:
  name: bills-api
  namespace: egs1
spec:
  ports:
  - port: 8000
    protocol: TCP
    name: bills-api
  selector:
    app: bills-api
  type: NodePort