---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bills-db
  namespace: jpcg
spec:
  selector:
    matchLabels:
      app: bills-db
  template:
    metadata:
      labels:
        app: bills-db
    spec:
      containers:
      - name: bills-db
        image: registry.deti:5000/billsdivider/billsdb:08062022
        ports:
        - containerPort: 3306
          name: bills-db
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: bills-db
  namespace: jpcg
spec:
  ports:
  - port: 3306
    protocol: TCP
    name: bills-db
  selector:
    app: bills-db
  type: NodePort