---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bills-api
  namespace: billsapi-jpcg
spec:
  selector:
    matchLabels:
      app: bills-api
  template:
    metadata:
      label:
        app: bills-api
    spec:
      containers:
      - name: bills-api
        image: registry.deti:5000/bills-api-jpcg:v1
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
