---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bills-db
  namespace: egs1
spec:
  selector:
    matchLabels:
      app: bills-db
  template:
    metadata:
      labels:
        app: bills-db
    spec:
      containers:
      - name: bills-db
        image: registry.deti:5000/billsdivider/billsdb:08062022
        ports:
        - containerPort: 3306
          name: bills-db
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: billsdb-secrets
              key: db_password
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: bills-pvc-claim
---
apiVersion: v1
kind: Service
metadata:
  name: bills-db
  namespace: egs1
spec:
  ports:
  - port: 3306
    protocol: TCP
    name: bills-db
  selector:
    app: bills-db
  type: NodePort