---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bills-mysql
  namespace: jpcg
spec:
  selector:
    matchLabels:
      app: bills-db
  template:
    metadata:
      labels:
        app: bills-db
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.21
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: flaskapi-secrets
              key: db_root_password
        ports:
        - containerPort: 3306
          name: mysql-port
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: bills-mysql
  namespace: jpcg
spec:
  ports:
  - port: 3306
    protocol: TCP
    name: bills-db
  selector:
    app: db
  type: NodePort