#To run and build in BillsAPI dir: sudo docker-compose -f deploy/docker-compose.yml  up --build
#To run without build: sudo docker-compose -f deploy/docker-compose.yml  up

version: "3"
services:
    bills-api:
        container_name: bills-api
        links:
            - bills-db
        image: bills-api
        build:
          context: ..
          dockerfile: deploy/Dockerfile.api
        ports:
            - "8000:8000"
    bills-db:
        container_name: bills-db
        image: mysql:8.0.21
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ../src/db/entry:/docker-entrypoint-initdb.d/:ro
            - ../src/db/data:/var/lib/mysql